# Crear conjuntos de datos de entrenamiento y validación

In [1]:
# Importar librerías
import pandas as pd
import os
from sklearn.model_selection import train_test_split

In [2]:
# Cargar los datos procesados
df = pd.read_parquet('../../data/processed/COVID19MEXICO_Processed.parquet')

# Inspeccionar las primeras filas de los datos procesados
df.head()

,ORIGEN,SECTOR,ENTIDAD_UM,SEXO,ENTIDAD_NAC,ENTIDAD_RES,MUNICIPIO_RES,TIPO_PACIENTE,INTUBADO,NEUMONIA,...,DEFUNCION,AÑO_ACTUALIZACION,MES_ACTUALIZACION,DIA_ACTUALIZACION,AÑO_INGRESO,MES_INGRESO,DIA_INGRESO,AÑO_SINTOMAS,MES_SINTOMAS,DIA_SINTOMAS
0,2,12,9,2,9,9,9,1,-2,2,...,2,2024,4,23,2023,2,26,2023,2,22
1,2,6,5,1,5,5,28,1,-2,2,...,2,2024,4,23,2023,3,24,2023,3,19
2,1,12,9,1,9,9,12,1,-2,2,...,2,2024,4,23,2023,3,2,2023,3,1
3,2,12,16,2,16,16,41,1,-2,2,...,2,2024,4,23,2023,3,9,2023,3,6
4,2,12,3,1,15,3,3,1,-2,2,...,2,2024,4,23,2023,6,12,2023,6,9

In [3]:
# Separar las variables dependiente e independiente
X = df.drop(columns=['DEFUNCION'])
y = df['DEFUNCION']

# Separar el conjunto de prueba (20% de los datos)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

### Almacenar los datos de entrenamiento y validación

In [16]:
# Ruta de la carpeta donde se guardaran los datos procesadoos
folder_path = '../../data/processed/'

# Verificar si la carpeta no existe y crearla si es necesario
if not os.path.exists(folder_path):
    os.makedirs(folder_path)

# Guardar datos de entrenamiento
X_train.to_parquet(folder_path + 'X_train.parquet', index=False)
pd.DataFrame(y_train).to_parquet(folder_path + 'y_train.parquet', index=False)

# Guardar datos de validación
X_test.to_parquet(folder_path + 'X_test.parquet', index=False)
pd.DataFrame(y_test).to_parquet(folder_path + 'y_test.parquet', index=False)